### ISSUE TITLE
Piecewise function feeding into intermediary node

### ISSUE THREAD

**Issue by pabogdan** [project-rig/nengo_spinnaker#46] opened 2015-07-15 10:53 UTC
Have tried running the following script using nengo_gui and get the exception at  the bottom of the page. It works using nengo, but fails with nengo_spinnaker, causing arbitrary cores to go into RTE.

``` python
from nengo.utils.functions import piecewise
import nengo
import numpy as np

model = nengo.Network("Piecewise bug")

with model:
    # Piecewise controller
    some_control = nengo.Node(output=piecewise({0: 1, 2: 0}))
    # Some input into A
    some_input = nengo.Node(output=lambda t: [np.pi / 2, np.pi / 4])
    # Intermediary node
    enabled = nengo.Node(size_in=1)
    # Some ensemble
    A = nengo.Ensemble(100, 2, radius=1.6)
    # Control signal feeds into intermediary node
    nengo.Connection(some_control, enabled)
    # Intermediary node inhibits population A
    nengo.Connection(enabled, A.neurons, transform=[[-2.5]] * A.n_neurons)
    # Some input in A just to check that inhibition works
    nengo.Connection(some_input, A)
```

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\nengo_gui\nengo_gui\page.py", line 443, in runner
    self.sim.run_steps(self.sim.max_steps)
  File "C:\nengo_spinnaker\nengo_spinnaker\simulator.py", line 179, in run_steps
    self._run_steps(n_steps)
  File "C:\nengo_spinnaker\nengo_spinnaker\simulator.py", line 247, in _run_steps
    status = self.controller.get_processor_status(p, x, y)
  File "c:\Python27\lib\site-packages\rig\utils\contexts.py", line 172, in f_
    return f(self, *args, **new_kwargs)
  File "c:\Python27\lib\site-packages\rig\machine_control\machine_controller.py", line 531, in get_processor_status
    state["rt_code"] = consts.RuntimeException(state["rt_code"])
  File "c:\Python27\lib\site-packages\enum\__init__.py", line 330, in __call__
    return cls.__new__(cls, value)
  File "c:\Python27\lib\site-packages\enum\__init__.py", line 642, in __new__
    raise ValueError("%s is not a valid %s" % (value, cls.__name__))
ValueError: 185 is not a valid RuntimeException
```

The value of the error seems random, it's rarely the same.

**Comment by mossblaser** [comment] 2015-07-15 10:55
It is worth highlighting that the RTE'd cores' IOBUFs are filled to the brim with unexpected key messages.

@pabogdan could you copy a few sample lines from the IOBUF of a RTE'd core resulting from running this snippet?

**Comment by pabogdan** [comment] 2015-07-15 10:59
The following is output repeatedly onto the terminal

```
[MCPL Rx] Unknown key 00000098
[MCPL Rx] Unknown key 000000a4
[MCPL Rx] Unknown key 000000b0
[MCPL Rx] Unknown key 000000bc
[MCPL Rx] Unknown key 000000c8
[MCPL Rx] Unknown key 000000d4
[MCPL Rx] Unknown key 000000e0
[MCPL Rx] Unknown key 00000080
[MCPL Rx] Unknown key 00000081
[MCPL Rx] Unknown key 00000082
[MCPL Rx] Unknown key 00000083
[MCPL Rx] Unknown key 00000084
[MCPL Rx] Unknown key 00000085
[MCPL Rx] Unknown key 00000086
[MCPL Rx] Unknown key 00000087
[MCPL Rx] Unknown key 00000088
[MCPL Rx] Unknown key 0000008c
```

**Comment by mundya** [comment] 2015-07-15 11:32
This is the passthrough node to ensemble bug.

**Comment by mundya** [comment] 2015-07-15 11:32
Sorry, to neurons.

**Comment by mundya** [comment] 2015-07-30 09:52
Closing as this is a duplicate of #30

**Closed as completed by mundya** 2015-07-30 09:52 UTC
